### ISSUE TITLE
Introduce pyogrio in addition to fiona

### ISSUE THREAD

**Issue by cheginit** [mhweber/ICRW8_Geospatial_Workshop#14]
In the slides notebook, I highly recommend introducing [PyOGRIO](https://pyogrio.readthedocs.io/en/latest/) package as an alternative library to `fiona` for reading GDAL supported data. You can also pass `engine=pyogrio` to `geopandas.read_file` to take advantage of this library. This allows to pass `use_arrow=True` among some other kwargs to this function that can further speed up reading large files such as NHDPlus. You can mention that `fiona` supports a wider range of GDAL supported files but is slow for large datasets.

Moreover, I recommend at least mentioning (Geo)Parquet and Feather formats as an alternative to more mature geospatial formats.

**Comment by cheginit** [comment]
I use `pyogrio` in `pynhd.nhdplus_l48` function. You can check it out [here](https://github.com/hyriver/pynhd/blob/b5441b1babc979db3845d0468483e5ac48b6cf6f/pynhd/network_tools.py#L825).

**Comment by mhweber** [comment]
Thanks @cheginit , just finished adding `pyogrio` to slides notebook (and to environment) and will push update shortly
