### ISSUE TITLE
Can't use nhdplusTools::get_characteristics_metadata()

### ISSUE THREAD

**Issue by mhweber** [mhweber/ICRW8_Geospatial_Workshop#4]
@dblodgett-usgs  - can't render updated .qmd - error line 465:
```
 nawqa_chars <- nhdplusTools::get_characteristics_metadata()
```

installed nhdplusTools from hydroloom branch, but get:
```
Error in curl::curl_fetch_disk(url, x$path, handle = handle): Failed to open file 
C:\Users\mweber\AppData\Roaming\R\data\R\nhdplusTools\metadata_table.tsv. 
```
Seems to be coded to look in wrong directory or not installing metadata_table.tsv with the `hydroloom` branch install of `nhdplusTools`

**Comment by dblodgett-usgs** [comment]
Does `C:\Users\mweber\AppData\Roaming\R\data\R\nhdplusTools` not exist?

**Comment by dblodgett-usgs** [comment]
I'm pushing what I think should be a fix now unless `C:\Users\mweber\AppData\Roaming\R\data\R` isn't writable? Try the latest.

**Comment by mhweber** [comment]
Just ran 
`remotes::install_github("doi-usgs/nhdplusTools@hydroloom"` 
but still get 
`Error in curl::curl_fetch_disk(url, x$path, handle = handle): Failed to open file C:\Users\mweber\AppData\Roaming\R\data\R\nhdplusTools\metadata_table.tsv.`

I might be missing a step that needs to happen?  Checked and `C:\Users\mweber\AppData\Roaming\R\data\R` is writable, but there is no nhdplusTools folder

**Comment by dblodgett-usgs** [comment]
hmmm... https://github.com/DOI-USGS/nhdplusTools/commit/2cb81da38982cb75104a319860e78f4ed0db78e2 should have done it. 

For now, just set `nhdplusTools::nhdplusTools_data_dir(tempdir())` and it should work?

**Comment by mhweber** [comment]
`remotes::install_github("DOI-USGS/nhdplusTools@2cb81da")
library(nhdplusTools)
nhdplusTools::nhdplusTools_data_dir(tempdir())`

did the trick - not sure why but had to use `nhdplusTools::nhdplusTools_data_dir(tempdir())` to get it to take.
